### PR TITLE
Add popularity sorting options for books

### PR DESCRIPTION
**Pull request by fuszti**
Now the user can sort the /books by the view_count. It is the #1712 feature request.

Unit tests are added too.

### CODE REVIEW

**Comment by fuszti** [comment]
@CodiumAI-Agent /review

**Comment by ssddanbrown** [comment]
Thanks for offering this @fuszti and sorry for the late response. Personally I'm not too convinced of the value of adding this feature, since there's been little desire for this so far and we already list a few of the most popular books in this view. Plus if we add this here it would also be expected in the shelves view, adding a little complexity there too.

**Comment by ssddanbrown** [comment]
I'm going to go ahead and close this off as per my comment above.

**Comment by fuszti** [comment]
Oh wow, I somehow missed your previous comment. Thank you for responding to my PR. I understand your point, no worries.

**Pull request closed without merging**
