### PR TITLE
Adding nextcloud for third party auth

### PR DESCRIPTION
**Pull request by sebclemens**
**Request:**

We want to use our existing nextcloud instance for authentification.

**Solution:**

Add nextcloud to social providers by using the already implemented socialite providers library.

### CODE REVIEW

**Comment by ssddanbrown** [comment]
Thanks for offering this @sebclemens, but did you come across #2607 or #2397?

My comments made here still apply: https://github.com/BookStackApp/BookStack/pull/2607#issuecomment-819027156
Upon that, we now have an OIDC option which would replace the default logic when active, although I'm not sure if nextcloud offers itself as an OIDC identity provider.

**Comment by sebclemens** [comment]
I spend a few hours on this. Nextcloud does not support OIDC. The plugin which adds this functionality did not work in my case.

But https://github.com/BookStackApp/BookStack/blob/release/dev/docs/logical-theme-system.md looks nice and could actually make my PR obsolete.

**Comment by sebclemens** [comment]
I solved this with the logical theme system docs. Please update the docs at bookstackapp.com, I spend a lot of time and didn't find it.

**Comment by putt1ck** [comment]
@sebclemens any chance you could share your solution for getting Bookstack to auth with NC via the logical theme system?

**Comment by MarioOsswald** [comment]
I tried yesterday the available NextCloud OIDC App from https://github.com/H2CK/oidc
The Purpose of this app is to use NC as the identity provider. I came close to get this working, but could not solve an issue with the Issuer definition, in particular, I guess, it's a rewrite problem or something related to it.

The details are:
I specified in BS .env file
OIDC_ISSUER=https://mynextclouddomain.tld
When I try a browser request with "https://mynextclouddomain.tld/.well-known/openid-configuration", the NC nginx redirects correctly to "https://mynextclouddomain.tld/index.php/.well-known/openid-configuration" and displays all the desired details, among them at first line 'issuer: "https://mynextclouddomain.tld/"'.
The problem is that BS doesn't get the results from the redirected URL. Instead, I receive an error 
"OIDC Discovery Error: Error discovering provider settings from issuer at URL https://mynextclouddomain.tld/.well-known/openid-configuration". The request from BS is not redirected the way the browser request was.

My approach was to change the .env variable to
OIDC_ISSUER=https://mynextclouddomain.tld/index.php
This solves the discovery problem, but then leads to an error message like
"OIDC Discovery Error: Unexpected issuer value found on discovery response". There is then an obvious mismatch, since on BS's side the issuer variable includes the index.php (OIDC_ISSUER=https://mynextclouddomain.tld/index.php), while the discovery response delivers only 'issuer: "https://mynextclouddomain.tld/"'.

A "curl https://mynextclouddomain.tld/.well-known/openid-configuration" delivers
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>

while a  "curl https://mynextclouddomain.tld/index.php/.well-known/openid-configuration" delivers the desired results.

I'm not experienced enough with NC or nginx redirect / rewrite features. Since the browser redirects correctly (without any required change from my side), I thought that's enough. I tried a few configurations, with no success. But probably someone more experienced has an immediate idea what to do so that a curl request is also redirected correctly. If so, I guess, BS will also auto discover correctly.

**Pull request closed without merging**
