### PR TITLE
Implementation of Nextcloud OAuth authentication

### PR DESCRIPTION
**Pull request by artur-shaik**
As https://github.com/SocialiteProviders/Providers/pull/632 is already merged, this implementation use it for authentication with Nextcloud.

### CODE REVIEW

**Comment by artur-shaik** [comment]
Looks like repo needs `composer update` command to make it work?

**Comment by Tealk** [comment]
@artur-shaik Is this done via oAuth2?

**Comment by artur-shaik** [comment]
> @artur-shaik Is this done via oAuth2?

Exactly.

**Comment by Tealk** [comment]
> Exactly.

Why don't you name it oAuth2, then it would be more general and users would know that they can include other services as well.
I for example would use it for MailCow ;)

**Comment by artur-shaik** [comment]
I wish to have generic OAuth provider in this app, too. But authentication implemented with third party library for php called Socialite. So I decide to implement Nextcloud support in that library to easily integrate it in Bookstack.

I think, you can try to substitude your app credentials and see what happen, with this patch.

**Comment by Tealk** [comment]
I will definitely try that out, then all services I have would be accessible via one instance.

**Comment by artur-shaik** [comment]
> I will definitely try that out, then all services I have would be accessible via one instance.

I just realized that this will not work. There are field access values that are unique for Nextcloud.

So, my advise for you is to implement your provider as Socialized plugin and use it on your BookStack instance as I do on my own. Actually you can just copypaste base classes and change it regarding you provider.

**Comment by ssddanbrown** [comment]
Thanks for offering this PR @artur-shaik, But I've come to the decision I don't want to grow out the supported third-party social provides much further, at least without a high level of benefit/request from the user-base. It's not a large amount of work to initially implement but it gets troublesome attempting to support people here when issues eventually arise.

Within the latest release, v21.04, I've added a system where you can perform some level of back-end customization. Details on this system can be seen here: https://github.com/BookStackApp/BookStack/blob/release/dev/docs/logical-theme-system.md
It's still in the testing stages, and I'm looking for feedback on it, but it should be possible to use additional socialite providers via this system, An example of this is shown at the bottom using Reddit which I tested during development of that system.

**Pull request closed without merging**
