### PR TITLE
#3166 Allow disable SMTP certificate verification

### PR DESCRIPTION
**Pull request by MKaterbarg**
While I don't recommend using this, I can see some users needing this for testing. This relates to request # 3166

### CODE REVIEW

**Comment by ssddanbrown** [comment]
Thanks for offering this @MKaterbarg.

What worries me about introducing this is that it will be used to fix SSL/TLS issues that should be addressed properly via other means. I feel people will enable this, see it fixes their issue, then presume they require to have this option enabled.

To me, If they've specifically enabled an encryption option, they should want a secured setup instead of opting to disable security controls. 

---

Upon the above, if there is found to be a valid case to include this, we'd also need to consider the following:

- We'd need to know when these actions take affect. Only on certain `MAIL_ENCRYPTION` options? Which ones?
- We'll need to move to Symfony mailer soon. Can all the required settings here be used with that library?
- Might be tricky but would be great to have a test cover this as such functionality an option can easily be forgotten and become broken, especially with mailer changes on the horizon.

**Comment by MKaterbarg** [comment]
@ssddanbrown  I do share your concerns. Maybe it should be an undocumented feature?

From my initial findings, I do believe the same approach should work for Symfony mailer

**Comment by ssddanbrown** [comment]
>  I do share your concerns. Maybe it should be an undocumented feature?

But then we'd just be supporting an undiscoverable feature. I'm still not fully sure what the use-case is to be honest, outside of being a work-around of security. 

> From my initial findings, I do believe the same approach should work for Symfony mailer.

Some documentation (Or links to docs) of how this would work would be ideal. I'd have to be sure to ensure we're not adding functionality we cannot support. 

Out of interest, Do you specifically have a need for this option? If so, clarity on your use-case may help me understand the need for this.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up on this I'll close this off but feel free to still comment and this can always be re-opened if needed.

**Pull request closed without merging**
