### PR TITLE
Add BookRevision

### PR DESCRIPTION
**Pull request by FrodeMMeling**
This is still WIP

Just wondering if this is something you would consider merging?
This will make it possible to create Book revisions, not only Page revisions.

Todo:
- [ ] Add Chapters also to Book revision
- [ ] What to do if no Pagerevision exist. Force create ?
- [ ] Add basic GUI
- [ ] Add testing

Future features:

- Diff comparisons between BookRevisions
- Guest users to request changes on Book level (group of pages changed). Like a pull request on git.
...

### CODE REVIEW

**Comment by ssddanbrown** [comment]
Hi @FrodeMMeling,
Sorry for the mega long response time. 

As it stands this is currently not something I'd consider merging. I can't currently really see the benefits to existing BookStack users with implementing Book Revisions. Really, It's just the name and description that's actually contained within the book. Implementing full revisioning including the included content of a book, which may have some use, will be a logical nightmare , especially as you consider the permissions system, requiring a lot of code and, more importantly, maintenance effort around those core BookStack elements.

**Comment by FrodeMMeling** [comment]
Ok. We will implement it ourselves then. We do not use it for books, but for technical specs. Then this revisioning is very handy. Thanks for the response.

Frode Marton Meling
IT Manager
Salt Ship Design

________________________________
Fra: Dan Brown <notifications@github.com>
Sendt: Saturday, September 19, 2020 1:37:44 PM
Til: BookStackApp/BookStack <BookStack@noreply.github.com>
Kopi: Frode Marton Meling <fm@saltship.com>; Mention <mention@noreply.github.com>
Emne: Re: [BookStackApp/BookStack] Add BookRevision (#1816)


Hi @FrodeMMeling<https://github.com/FrodeMMeling>,
Sorry for the mega long response time.

As it stands this is currently not something I'd consider merging. I can't currently really see the benefits to existing BookStack users with implementing Book Revisions. Really, It's just the name and description that's actually contained within the book. Implementing full revisioning including the included content of a book, which may have some use, will be a logical nightmare , especially as you consider the permissions system, requiring a lot of code and, more importantly, maintenance effort around those core BookStack elements.

**Comment by wojosc** [comment]
Also full history for the levels book and even shelf would be useful.

**Comment by ssddanbrown** [comment]
Will therefore close based on the above.

**Pull request closed without merging**
