### PR TITLE
[API] add priority

### PR DESCRIPTION
**Pull request by rouet**
[API] add priority in book read
[API] add priority in chapter create and update
[API] add priority in page create and update

I propose a pull request in order to add the possibility of modifying the priority field of pages and chapters by the api, this in order to allow sorting a book using the api.
This proposal solves the problem posed by @riton in ticket #4298.
I also added in addition to display the priorities when a book is requested by the rest api.
We have tested and validated it internally.
I am not a Laravel specialist, but if it is necessary to add the corresponding tests, I can do it, but it will need help on the scenarios to be tested.

Regards.

### CODE REVIEW

**Comment by ssddanbrown** [comment]
Thanks for this @rouet.

> We have tested and validated it internally.

Is it currently working on page create? Not tested it myself but looking at the existing code I'd be surprised if priority was filled here.

> I am not a Laravel specialist, but if it is necessary to add the corresponding tests, I can do it, but it will need help on the scenarios to be tested.

Tests would be ideal. For the update endpoints, you can update the existing `test_update_endpoint` tests to include priority. [Example of such test](https://github.com/BookStackApp/BookStack/blob/0323ebccd3747cc757819e265ccad87889ec0acf/tests/Api/ChaptersApiTest.php#L127). 
For the create endpoints, it'd be best to have new tests for those, so a `test_create_applies_correct_priority` test cases for both chapters and pages. You can follow the `test_create_endpoint` test cases as an example in the relevant `PagesApiTest` and `ChaptersApiTest` classes.

Additionally, could you update the relevant example API requests/responses within this directory?:
https://github.com/BookStackApp/BookStack/tree/1e220c473fa71a412918a8e55b63949019b40744/dev/api

**Comment by rouet** [comment]
> Thanks for this @rouet.
> 
> > We have tested and validated it internally.
> 
> Is it currently working on page create? Not tested it myself but looking at the existing code I'd be surprised if priority was filled here.
> 

my tests were not complete, indeed, it does not work at creation, should we make it work? because I have the impression that the modification of the code will be much more consequent.

> > I am not a Laravel specialist, but if it is necessary to add the corresponding tests, I can do it, but it will need help on the scenarios to be tested.
> 
> Tests would be ideal. For the update endpoints, you can update the existing `test_update_endpoint` tests to include priority. [Example of such test](https://github.com/BookStackApp/BookStack/blob/0323ebccd3747cc757819e265ccad87889ec0acf/tests/Api/ChaptersApiTest.php#L127). For the create endpoints, it'd be best to have new tests for those, so a `test_create_applies_correct_priority` test cases for both chapters and pages. You can follow the `test_create_endpoint` test cases as an example in the relevant `PagesApiTest` and `ChaptersApiTest` classes.
> 
> Additionally, could you update the relevant example API requests/responses within this directory?: https://github.com/BookStackApp/BookStack/tree/1e220c473fa71a412918a8e55b63949019b40744/dev/api

ok i'll take care of that

**Comment by ssddanbrown** [comment]
> it does not work at creation, should we make it work?

Ideally yes, but if you're uncomfortable making further changes you can ignore this but be sure to still add a test, so that I have a failing test case to address before merging.

**Comment by rouet** [comment]
Hi

I've push a last version (if it's ok) with priority set correctly on insert.
I wrote or modify some tests
I modify the Json examples

regards

**Comment by ssddanbrown** [comment]
Thanks for this @rouet,
Now merged in to development to be part of the next feature release.
Made a few last minor changes in 9ca1139ab0d0f5dd8d8eda4e9cd96f6c33530344.

**Pull request merged**
