### PR TITLE
Added password history, complexity, and expiry validations

### PR DESCRIPTION
**Pull request by bosaleh**
This PR implements the following validations for passwords:

1- Password history: stops the user from re-using a password they have previously used. The number of passwords to be validated can be set in the PASSWORD_HISTORY environment variable.

2- Password expiry: forces the user to reset their password after a specified period. The number of days before expiry can be set in the PASSWORD_MAX_AGE environment variable.

3- Password lock: Stops the password from being changed until a specified period has elapsed. The number of days until a password can be changed can be set in the PASSWORD_MIN_AGE environment variable.

4- Password complexity: uses Laravel's built-in password validation to enforce password policies that can be set as environment variables. Please see .env.example.complete for the complete list of complexity validations.

### CODE REVIEW

**Comment by ssddanbrown** [comment]
Thanks for offering this PR @bosaleh, but to be honest I'm not keen on adding a whole range of options to support, which can add new scenarios/paths to consider, especially where much of this functionality has not been previously requested.

The most relevant existing request related to this would be #1856, to allow a configurable password policy. 
We may want to take things in a different approach rather than just providing many direct options (env or UI) to control requirements. You can comment there, or :+1: the original post, to show support.

Otherwise, for the other features, you could open specific feature requests to provide an opportunity to describe the specific benefits of adding such options, and allow community interest to be gauged over time to indicate requirement/need from our user-base.

**Comment by bosaleh** [comment]
Thanks @ssddanbrown, I agree that these are niche features that few will need, but I had to implement them on our installation anyway.

If you want I could create a new PR with just the password complexity rules mentioned in #1856 as that only adds a few lines in AuthServiceProvider.

**Comment by ssddanbrown** [comment]
Thanks for your understanding @bosaleh!

> If you want I could create a new PR with just the password complexity rules mentioned in https://github.com/BookStackApp/BookStack/issues/1856 as that only adds a few lines in AuthServiceProvider.

Thanks for the offer, but to be honest, I'm still not too comfortable adding a variety of options for this, especially where fairly tightly tied to the underling Laravel options. I'd want to see a bit more demand & input regarding scenario/control before adding official env/UI options.

An alternative option is that we could maybe make it easier to use [our logical theme system](https://github.com/BookStackApp/BookStack/blob/development/dev/docs/logical-theme-system.md) to define custom password rules (may already be possible to define custom rules via this system), but not sure if there'd be active use of this if added as an option.

**Comment by melat0nin** [comment]
> Thanks @ssddanbrown, I agree that these are niche features that few will need, but I had to implement them on our installation anyway.
> 
> If you want I could create a new PR with just the password complexity rules mentioned in #1856 as that only adds a few lines in AuthServiceProvider.

Would you be willing to share this as a gist, for those willing to make (and maintain) the changes in their own instance?

**Comment by melat0nin** [comment]
Just found this snippet on Discord from @ssddanbrown, which does the trick: https://discord.com/channels/578552496637739008/985537128505163786/1050088597686071386

**Comment by ssddanbrown** [comment]
@melat0nin Ah, sorry, I had forgot to respond to your comment above.

Edit: To help others that might come across this, here's the referenced content from Discord:

---

Can be hacked via the logical theme system.
Following the getting started part of the logical theme system docs:

Use a functions.php following this:

```php
<?php

use BookStack\Facades\Theme;
use BookStack\Theming\ThemeEvents;
use Illuminate\Validation\Rules\Password;

Theme::listen(ThemeEvents::WEB_MIDDLEWARE_BEFORE, function() {
    Password::defaults(function() {
        return Password::min(12)
            ->mixedCase()
            ->symbols()
            ->numbers();
    });
});
```


Tweak rules as desired.
Note: This is customized logic and not officially supported, may break upon updates.
Changes may not be correctly reflected in certain errors (Maybe error mesages, API doc details etc...)

**Comment by melat0nin** [comment]
@ssddanbrown no problem, I see you've been plenty busy with v24.02!

**Pull request closed without merging**
