### PR TITLE
.vscode folder is added in .gitignore file

### PR DESCRIPTION
**Pull request by esakkiraja100116**
- `.vscode` folder added in `.gitignore` file.

### CODE REVIEW

**Comment by ssddanbrown** [comment]
@esakkiraja100116 Happy to accept the change to the `.gitignore` file since vscode is popular.

I would not look to accept the `.env.example` change though, since that file is used for production/release workflows as a base for the user env. Development mode should be opt-in, not a default.

**Comment by esakkiraja100116** [comment]
okay understand. Now I removed that line from `.env.example` file.

**Review by esakkiraja100116 — COMMENTED** [review]
`.vscode ` folder is added here!

**Comment by ssddanbrown** [comment]
Thanks!

**Pull request merged**
