### PR TITLE
Middleware to handle SSO variables

### PR DESCRIPTION
**Pull request by injektion**
Simple middleware to check if SSO variables are set, and auto login if they are.

As per issues #2223 #2180 #1500

### CODE REVIEW

**Comment by ricardojlrufino** [comment]
This can be important for integrating automatic authentication for help pages in third-party software

**Comment by ssddanbrown** [comment]
Thanks for offering this @injektion and apologies for my massively late reply.

I've been hesitant to merge this since, while it does provide some likely desired functionality, it would not be enough to close any of the linked issues. They all would need a slightly different implementation and/or would desire a much expanded set of options.

This is an area where configurability and exact implementation may vary wildly between use-cases so I'm not sure it's going to be something we can easily cater for by default.

Instead, the [logical theme system](https://github.com/BookStackApp/BookStack/blob/release/dev/docs/logical-theme-system.md) could be utilised to setup a custom logic implementation as needed. I've ensured this has a couple of middleware-based events included with the functionality of this PR in mind. For example, To roughly translate your pull request code, a `functions.php` file within the theme system would look like this:

```php
<?php

use BookStack\Access\LoginService;
use BookStack\Theming\ThemeEvents;
use BookStack\Facades\Theme;
use BookStack\Users\Models\User;
use Illuminate\Http\Request;

Theme::listen(ThemeEvents::WEB_MIDDLEWARE_BEFORE, function (Request $request) {

    // The name of the header which will contain the value to identify
    // the authorized user. You need to make sure this header is managed by the web server
    // or auth proxies before the request hits BookStack, so end users can't control the
    // value of this header.
    $authHeaderName = 'http-mail';

    // The BookStack user property that we'll match the header value
    // with to identify the user to authentication.
    $authUserAttribute = 'email';

    $authVarValue = $request->headers->get($authHeaderName);
    if ($authVarValue && !auth()->check()) {
        $user = User::query()->where($authUserAttribute, '=', $authVarValue)->first();
        if ($user) {
            $loginService = app()->make(LoginService::class);
            $loginService->login($user, 'custom_header_auth');
        }
    }
});
```

This can be implemented on an existing, current BookStack install without altering core app files. This kind of approach then allows customization and configurability where needed.
Full details on setting this up can be seen in the logical theme system docs: https://github.com/BookStackApp/BookStack/blob/release/dev/docs/logical-theme-system.md

_**Note**: Logic within the logical theme system is unsupported and unofficial. It has not been fully tested, nor have all angles of security been considered. BookStack updates may interfere with, or break, logic used._

I'll therefore close off this PR but if you have any objections to the above or any feedback regarding the logical theme system approach feel free to continue to comment.

**Comment by injektion** [comment]
Just circled back to this months later, and your template based solution was much better than middleware clog - switched our installs over to this instead of the SSO middleware and it's working smoothly... thank you for the pointer.

**Comment by ssddanbrown** [comment]
Thanks for confirming @injektion. Good to know this theme-based solution works for people!

**Comment by Namron10410** [comment]
Hello,
I want to perform an autologin on Bookstack with LDAP / SSO
I want to do it with HTTP / REMOTE_USER requests
I did not succeed following your advice above
Could you please explain to me the procedure to follow (in more detail)
thanks in advance

**Comment by cjs59** [comment]
> Responding to https://github.com/BookStackApp/BookStack/pull/2289#issuecomment-857164663

For anyone using this code with more recent versions of BookStack, change the first use line to:

use BookStack\Users\Models\User;

**Comment by pghope** [comment]
> For anyone using this code with more recent versions of BookStack, change the first use line to:
> 
> use BookStack\Users\Models\User;

Huge thanks for adding this here @cjs59.

I was seeing failed new login attempts in version 23.06 onwards - got a 500 error and generic error page 'An unknown error occurred'.

**Comment by ssddanbrown** [comment]
I've updated [my example above](https://github.com/BookStackApp/BookStack/pull/2289#issuecomment-857164663) to align with current BookStack versions (tested on v23.10.2).
This also updates the logic to log-in via the app's `LoginService` which allows this to work with some other system features where desired (MFA, Audit-log login tracking, theme system, email confirmation).

**Comment by cjs59** [comment]
The updated example only works for HTTP request headers - if you need a server header like REMOTE_USER, you need this line instead:

$authVarValue = $request->server->get($authHeaderName);

**Comment by mig5** [comment]
This works great, the only issue is I found that there could be a redirect loop if you had MFA enabled on your account in Bookstack. I had to disable it to avoid a strange 302 redirect on the /mfa/verify route. (Fortunately I can set up MFA with my SSO/IDP provider).

**Comment by JasperE84** [comment]
> This can be implemented on an existing, current BookStack install without altering core app files. This kind of approach then allows customization and configurability where needed. Full details on setting this up can be seen in the logical theme system docs: https://github.com/BookStackApp/BookStack/blob/release/dev/docs/logical-theme-system.md
> 
> _**Note**: Logic within the logical theme system is unsupported and unofficial. It has not been fully tested, nor have all angles of security been considered. BookStack updates may interfere with, or break, logic used._
> 

Hi @ssddanbrown, any chance we can make this procedure also update the LDAP group memberships for the logged in user? I've successfully implemented the SSO by header using the sample provided, but once the user made his first manual login and the user exists in bookstack, the LDAP group memberships do not seem to be updated from the AD anymore. (Considering that I also guess the user will remain a bookstack user with associated rights once the LDAP backend user is deleted)

**Comment by JasperE84** [comment]
> Hi @ssddanbrown, any chance we can make this procedure also update the LDAP group memberships for the logged in user? 

This idea seemed rather complex to implement, I've now moved to SAML with my bookstack Entra App registration (with Entra application proxy, providing an authed Entra reverse proxy to my LAN docker container (just like cloudflared proxy can). No need to open ports on my router this way and with SSO from Microsoft Entra seamless sign on. Works quite nice, sill trying to figure out now how to not require the user to click the login link top right at all now. (Once login is clicked it auto chooses SAML using the env variable, but why require the user to click login at all)

**Comment by ssddanbrown** [comment]
> Works quite nice, sill trying to figure out now how to not require the user to click the login link top right at all now. (Once login is clicked it auto chooses SAML using the env variable, but why require the user to click login at all)

@JasperE84 Is that with the `AUTH_AUTO_INITIATE=true` option enabled? That option auto-starts login if there's only a single SSO auth option. If public access is enabled though, the user will have to first navigate to the login screen since they may be considered a guest/non-logged-in user. If public access is disabled, this should be fairly seamless, as users are redirected to the login screen automatically (if not already logged in), where authentication will be auto initiated.

**Comment by JasperE84** [comment]
> If public access is disabled, this should be fairly seamless, as users are redirected to the login screen automatically (if not already logged in), where authentication will be auto initiated.


Thats excellent, I should have thought of that. Thanks! I will disable public access tomorrow and try that out!

**Pull request closed without merging**
