### PR TITLE
Fix An Exception 

### PR DESCRIPTION
**Pull request by abublihi**
Fix an exception error 
```
ErrorException
Declaration of BookStack\Http\Middleware\TrustProxies::handle($request, Closure $next) should be compatible with Fideloper\Proxy\TrustProxies::handle(Illuminate\Http\Request $request, Closure $next) 
```

### CODE REVIEW

**Comment by ssddanbrown** [comment]
Thank you for the pull request @abublihi.
Would you be able to confirm when this error would actually appear? Just intrigued at why this issue has not shown up earlier.

**Comment by abublihi** [comment]
This issue appeared after the installation and configuration immediately,

The have not appeared after I have installed the release branch, it only appears on the master branch.

**Comment by abublihi** [comment]
the error accord because of the  version of fideloper/proxy packge

version [3.3.4](https://github.com/fideloper/TrustedProxy/blob/3.3.4/src/TrustProxies.php#L51)
```php
    /**
     * Handle an incoming request.
     *
     * @param \Illuminate\Http\Request $request
     * @param \Closure                 $next
     *
     * @throws \Symfony\Component\HttpKernel\Exception\HttpException
     *
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        $this->setTrustedProxyHeaderNames($request);
        $this->setTrustedProxyIpAddresses($request);
        return $next($request);
    }
```


version [4.2.1](https://github.com/fideloper/TrustedProxy/blob/4.2.1/src/TrustProxies.php#L42)
```php
    /**
     * Handle an incoming request.
     *
     * @param \Illuminate\Http\Request $request
     * @param \Closure                 $next
     *
     * @throws \Symfony\Component\HttpKernel\Exception\HttpException
     *
     * @return mixed
     */
    public function handle(Request $request, Closure $next)
    {
        $request::setTrustedProxies([], $this->getTrustedHeaderNames()); // Reset trusted proxies between requests
        $this->setTrustedProxyIpAddresses($request);
        return $next($request);
    }
```

**Comment by ssddanbrown** [comment]
@abublihi Sure, I totally get what has changed and why this error might get thrown but I'm essentially curious as to why I have not seen this issue on my own system.

Would you be able to confirm your exact PHP version and operating system?

**Comment by abublihi** [comment]
Yes you are right.

Operating System: MacOs Sierra 
Php 7.1

**Comment by ssddanbrown** [comment]
I never managed to find how an error would be thrown but I'll stop digging. 

Thank you again @abublihi for this change. Will merge in to be part of v0.28.

**Pull request merged**
