### PR TITLE
Add a 'Create New Book' button on shelf list

### PR DESCRIPTION
**Pull request by cw1998**
A solution for #1260 .
image

Some notes:
- When a book is added, it is added to the top of the shelf. 
- When a book is added, you get redirected back to the shelf rather than the new book. This works for me, but may not work for the majority.

### CODE REVIEW

**Comment by ssddanbrown** [comment]
Great stuff, Thanks @cw1998. 

I'm currently in the middle of a design update (#1153) so I'll probably wait until that's merged into master (Couple of weeks) before I review and merge this. Looks good from a quick scan of the changes though!

**Comment by cw1998** [comment]
Hi @ssddanbrown , I've updated this PR after the merge of the 2019 design. I went for a blue "Create  New Book" button on an empty shelf rather than red (based on seeing orange text for adding a new chapter to an empty book) - hopefully this is correct.

**Comment by ssddanbrown** [comment]
Thanks again for this @cw1998.

All looked pretty good. Made a few logical changes, in addition to aligning some existing wording, in 7f3f6e65b9705beabbafa5ceba8636a74ac22138:
* I changed the addition of books to be an append instead of a prepend. I think this is what users will generally expect, and aligns with the analogy where you'd generally add a new book to the end of a shelf.
* As you mentioned in your original post, I updated the post-create redirect to navigate to the book since I think most people will go on to create book content and this behaviour aligns with the existing book creation process. 

All merged, ready for the next release!

**Comment by cw1998** [comment]
Awesome, thanks. I agree with the changes mentioned and they all make sense. I'll keep wording in mind next time too.
Looking forward to seeing the new design in a release!

**Pull request merged**
