### PR TITLE
changed PageContent.php to accept nested includes

### PR DESCRIPTION
**Pull request by jasonF1000**
tested and it works. 
We have implemented levels depths that can be configured as needed. ( via includeDepth variable)
This solves issue #2845

### CODE REVIEW

**Comment by jasonF1000** [comment]
hi @ssddanbrown, could you please review this pull request?

Thanks in Advance.

**Comment by ssddanbrown** [comment]
Thanks @jasonF1000 for offering this PR. A few of things:

- The code provided seems to have whitespace issues, mainly in that it seems to be using non-breaking spaces instead of normal spaces within the indentation, which breaks this as code.
- This loop only needs to be around `parsePageIncludes`, not ` blankPageIncludes` too. 
- Ideally I'd want to have testing added to cover this scenario (With some depth checking to ensure this sticks to three levels max).

There are existing tests to cover page includes in this file:
https://github.com/BookStackApp/BookStack/blob/development/tests/Entity/PageContentTest.php
Would you be comfortable in adding the requested testing?

### Note-to-self

If merged, this will need to be documented as a breaking change.

**Comment by jasonF1000** [comment]
Hi @ssddanbrown i followed your recommendation and fixed the space issue and change the loop that it is only around the parsePageIncludes.

But i feel not so comfortable to add the testings, therefore i have to low experience with PHP. Sorry :(

**Comment by ssddanbrown** [comment]
Thanks @jasonF1000, now merged for next release. 
I followed with up with 56f234d1ee046a84da163aaaa5048a2463dbabb1 to adjust formatting and add testing.

**Comment by jasonF1000** [comment]
@ssddanbrown thank you for taking over the testing part and for the implementation of the feature :)

**Pull request merged**
