### PR TITLE
Added Mermaid to MarkdownIt editor

### PR DESCRIPTION
**Pull request by cadavre**
This is really a simple PR with addition of [Mermaid](https://mermaid-js.github.io/) into MarkdownIt editor, that BookStack is using.

It allows to create Mermaid diagrams via Markdown with specific syntax.

This is a preview of how it works:

Zrzut ekranu 2021-04-27 o 14 19 00

This addresses #495 and #566 .

### CODE REVIEW

**Comment by ssddanbrown** [comment]
Thanks for offering this PR @cadavre but I'd really need my [concerns listed here](https://github.com/BookStackApp/BookStack/issues/495#issuecomment-628919106) addressed before considering support.

In addition, I'm fairly sure that on the latest version of BookStack this will only show the mermaid output within the preview window, not within the the actual page output after save, unless I'm missing something?

**Comment by cadavre** [comment]
Hah, I'm newbie to BookStack dev and looks like I went kind of too excited after Mermaid started to work in preview. Haven't thought that you're maintaining two different Markdown rendering engines. :o That seems like a pain in the ass. :/

> The current use-case for UML/Mermaid is weaker since we now have draw.io which has a lot of overlap and is well-suited to the use-case of multi-ability environments. I can see why those technically inclined may like UML/Mermaid, kind of want to use it myself tbh, but it's focusing on a narrow audience with a custom text syntax, which kind of opposes the idea/spirit of the project.

Markdown itself sounds like "focusing on a narrow audience with a custom text syntax" in comparison to WYSiWYG. I can see nothing wrong in adding Mermaid which can be accessed only via MD.

I believe we could add Mermaid rendering same as it is done for draw.io – graphs can be exported to .png for browsing mode. If I follow up with this kind of implementation, would it be ok for you to merge it?

**Comment by ssddanbrown** [comment]
> Markdown itself sounds like "focusing on a narrow audience with a custom text syntax" in comparison to WYSiWYG. I can see nothing wrong in adding Mermaid which can be "accessed" only via MD.

But now we're providing a narrow feature for an already narrowed audience, and this works against the alignment I'm intended to work towards with the editor to get to a place where you switch between modes easier.

> I believe we could add Mermaid rendering same as it is done for draw.io – graphs can be exported to .png for browsing mode. If I follow up with this kind of implementation, would it be ok for you to merge it?

I'd imagine people would still want to edit via mermaid text, This is going to introduce some significant complications to achieve.  In addition it introduces some further complications if accepted in the editor markdown since you now have mis-alignment with the API unless you're able to do things back-end.

To be honest, I can't imagine an implementation I'd be happy to merge at this time, especially as we look to change up the editors later this year and align the editing modes. Will mean wasted effort if done now. I'd rather look to see what's required, after the editor work, to allow people to optionally add "Mermaid" via our customization options (Accepting the limitations/caveats). 

I'll close off this PR for now though.

**Comment by mwatermolen** [comment]
Any chance we can re-evaluate this?

**Pull request closed without merging**
