### PR TITLE
add everything needed to use discord as social login provider

### PR DESCRIPTION
**Pull request by lommes**
- Go to  https://discordapp.com/developers/applications/me
- Create new app
- Choose app name which will be shown to the user during login/registration
- Add http(s)://yourbookstackurl/login/service/discord/callback as redirect
- create app
- add Client ID as value of DISCORD_APP_ID to .env
- add Client Secret as value of DISCORD_APP_SECRET to .env

### CODE REVIEW

**Comment by lommes** [comment]
This implements #903

**Comment by ssddanbrown** [comment]
Thanks @lommes, Will review and merge shortly.

On another note, Would you like to be an official BookStack member? I appreciate the effort you voluntarily provide around here so thought it might be good to make you official here on the BookStack GitHub org. You'll have abilities to manage issues and directly update code if required (Although I would ask anything fairly large to made as a reviewed pull request first). Nothing further would be expected of you, just remain polite and friendly as you currently do anyway.

**Comment by lommes** [comment]
@ssddanbrown Sure, feel free to add me to the organization! I feel kind of honored :)

**Comment by ssddanbrown** [comment]
Tested, Works as expected, Thanks again @lommes, Will merge in now

**Pull request merged**
