### PR TITLE
Customize colors in settings

### PR DESCRIPTION
**Pull request by james-geiger**
This is a placeholder to address #1380 creating a UI and storing settings for the css color variables for page, page draft, chapter, book, and shelf.

### CODE REVIEW

**Comment by james-geiger** [comment]
@ssddanbrown Do you see this having its own settings card or live within the existing card for customizing the app?

**Comment by james-geiger** [comment]
This didn't take as long as I'd initially expected, largely due to the fact that the future was kept in mind when writing the settings controller.

I decided to, for now, leave the colors where they are in the "customization" section because I think that makes the most sense.

I did have to add a number of new labels/descriptions, so one downstream effect of this PR will be that a number of languages will be missing translations for those added keys.

**Comment by ssddanbrown** [comment]
Awesome, Nice work @james-geiger. I'll review this soon. I would have said to live within the existing card anyway :+1:

**Comment by ssddanbrown** [comment]
Thank you for this @james-geiger, All worked great.

Before merging I tweaked up the UI a little just to take up less space in the settings view:

image

Will be in the next release.

**Pull request merged**
