### PR TITLE
[API] Recycle bin endpoints

### PR DESCRIPTION
**Pull request by bourdaisj**
Related to: https://github.com/BookStackApp/BookStack/issues/3372
This is a draft PR to discuss and make sure I'm on the right track.

### CODE REVIEW

**Comment by ssddanbrown** [comment]
Hi @Julesdevops, 
This is looking great so far, can't see any major things to change at this time.
Just let me know when all is implemented & ready from your side and I'll jump in for a full review.

**Comment by bourdaisj** [comment]
I think the three endpoints I already implemented are fine as-is.
I'm thinking about adding a fourth one, 'read', which would returns the full chain of deleted items (children & parents) with their ids as well as some (limited) informations about them.
Wdyt? @ssddanbrown

**Comment by ssddanbrown** [comment]
@Julesdevops I would prefer the most minimal approach that covers your use-case, which sounds like it may be covered by the existing three?

If (and only if) the extra detail was really needed I'd be tempted to say an additional parameter on the existing book/chapter/page/shelf  "read" endpoints might be better suited to avoid needing a more complex implementation for this specific use-case.

**Comment by ssddanbrown** [comment]
@Julesdevops Let me know your intention either way. No rush on the actual work but I'll be wrapping up the next feature release over the next week so, if you're happy with the current state, I can plan to sneak this in `v22.04` otherwise we can plan for a latter release.

**Comment by bourdaisj** [comment]
@ssddanbrown It already covers my use-case indeed. If someone is facing a more complex use-case someday I'd be happy to follow-up on this though.
I'll do a little pass on the code, doc and then I will mark this as ready for review

**Comment by ssddanbrown** [comment]
Thanks again for this @Julesdevops, Now merged for next release.

During review, I did make a series of changes detailed in commit ff8dadefee9e400bb46a54b301a8b701c4a0b61b. Everything was functionally great and high-quality, most of the changes I made were just alignment with existing codebase conventions. The main significant other change was around how entity children and parent details were provided back on the list response. If you have any queries on my changes feel free to ask.

I wasn't a fan of exposing internal namespacing for API use (`deletable_type`) but I saw the value in having this for identification and filtering, so I also followed this up with 0930e8519c508d46a848db93c76f258da5ee84a9 which simplifies all internal morph types within the database to simple `page/book/chapter/bookshelf` names instead of namespaces.

**Comment by bourdaisj** [comment]
@ssddanbrown Fair enough. Thanks for following up on this so quickly!

**Pull request merged**
