### PR TITLE
Addition of a user-selectable dark-mode option

### PR DESCRIPTION
**Pull request by ssddanbrown**
- [x] Most elements done, but still need to do editors, tables and final pass.
- [x] Toggled only by quick js check at the moment, checking via css media query. Need to make into user-preference toggle.
- [ ] Say thanks to domainzero

For #1234

### CODE REVIEW

**Comment by ssddanbrown** [comment]
bookstack local_ (1)

**Comment by over-soul** [comment]
@ssddanbrown, is there a way to let guest users select dark mode?

**Comment by ssddanbrown** [comment]
Should be an option on the home screen. See above the right-most "Recent Activity" card here:
https://demo.bookstackapp.com/

**Comment by whentotrade** [comment]
Would it be possible to also place this button to switch between dark/light mode on the books, shelf, chapters page sites, e.g. as another item in the "Actions" section below "Export"? This would make is possible to change theme on book/page sites also an not only on the main home screen.

**Comment by ssddanbrown** [comment]
@whentotrade Dark mode does not really relate to the items that the existing actions are centered around so I'd prefer not to add it there.  

Non guest users can toggle dark mode from any page via the top-right profile menu.

**Comment by whentotrade** [comment]
Ok, thanks. Then maybe just on the /books page. As there the "dark/light mode" open is missing when you click on the "Books" tab from the tab. While when you choose "books" as the standard homepage, the switch button is there in the overview. 

This is the "Actions area" on the upper left when setting "books" as the standard homepage in the settings (with switch button):
grafik

Where as this is the "Action area" when clicking the main "Books" tab on the top bar (without switch option)
grafik

Then main contant is the same - just the landing page selected as "books" in the settings shows the switch button while when clicking the "books" main tab the option is not visible.

Just a proposal and observation.

Thanks for the great work!

**Pull request merged**
