### PR TITLE
Books page as application home page

### LINKED ISSUE #615: Request: Books page as application home page
### For Feature Requests

Desired Feature: Allow the application homepage to be set to /books?

### PR DESCRIPTION
**Pull request by Abijeet**
Closes #615

### CODE REVIEW

**Comment by Abijeet** [comment]
@ssddanbrown - Ready for review.
 
Let me know if you'd like me to make any changes in the code.

Few items tested,

1. Setting the books page as homepage override the custom homepage option.
2. Book view toggle on home page works properly.
3. Removing the book homepage option reverts back to the previous home page.

**Comment by Abijeet** [comment]
Made a couple of minor adjustments based on some of the issues I found.

**Comment by mendiromania** [comment]
Great work as always Abijeet!

**Comment by ssddanbrown** [comment]
Thanks @Abijeet, All looked great and functioned well.

I done a little view clear-up so we only have layout, base templates in the root of the `views` folder and extracted the home-sidebar into its own view since it was used in multiple files. 

Thanks again, I know many people will be happy with this feature.

**Pull request merged**
