### PR TITLE
implement social auto registration feature

### PR DESCRIPTION
**Pull request by ibrahimennafaa**
Related to #574 

I added a setting to allow auto silent registration of user when social auth is used.

Few things to be aware of:
- enabling this setting would disable email verification for social auth but it's described under the setting + I think email verification for social auth is useless.
- if domain restriction is enabled => the auto social registration process respect it.
Missing: translation & probably better wording (my english is not perfect)

Missing: check of wording + translations

### CODE REVIEW

**Comment by ibrahimennafaa** [comment]
@ssddanbrown do you know why the unit tests are failing only for `PHP: 7.0.20`

**Comment by ibrahimennafaa** [comment]
test

**Comment by ibrahimennafaa** [comment]
retest

**Comment by ibrahimennafaa** [comment]
Anyone would like to review this? @Abijeet @ssddanbrown happy to discuss

**Comment by ChrisMcKee** [comment]
Sounds good; would be handy if you could restrict to only allow registration from social auth (restricts control of authentication to your github org or as configured in azure)

**Comment by ssddanbrown** [comment]
Thank you for this pull request @ibrahimennafaa. It is now merged although be aware I have made some changes to the system since which can be seen here:
https://github.com/BookStackApp/BookStack/commit/e60d11ee04161d16875d706110876c31f9064565

I thought there's quite a good chance that trust in a social service may differ between services so admins may want more control over this kind of registration logic. Therefore I changed the global setting in the interface for a set of `.env` options. 

For each $service you can now set a {$service}_AUTO_REGISTER and a {$service}_AUTO_CONFIRM_EMAIL option your `.env` file.
- AUTO_REGISTER will allow registration from login, even if registration
is disabled.
- AUTO_CONFIRM_EMAIL indicates trust and will mark new registrants as
'email_confirmed' and skip 'confirmation email' flow.

As part of my updates I also removed the additional registration logic from the SocialAuthService to reduce duplication so now send users down the normal registration flow at the controller-level. 

Massive thanks for getting this started, Will be in the next release which I'm hoping will be done in the next few days.

**Comment by ibrahimennafaa** [comment]
@ssddanbrown thanks for the updates! They all make sense to me.

Do you happen to know in which version this will be deployed?

Thanks!

**Pull request merged**
