### PR TITLE
WIP: 2019 design

### PR DESCRIPTION
**Pull request by ssddanbrown**
This is a WIP design update targeted for early 2019. It includes some functional aspects of the design as well as just styles.

### Design Goals

* Improved design consistency and feature usage throughout application.
* Provide a more modern, less "stock" feel.
* Cleanup of colour-scheme for easier customizability. 
* Lessen usage of glaring entity colours.
* Improved mobile usability.
* Increased functionality in core areas for improved app usage efficiency. (Book list sorting, for example)

### Early Preview (Comparison)

**Old Books List View**
bookstack_books_redesign_old

**New Books List View**
bookstack_books_redesign

### CODE REVIEW

**Comment by lucassmacedo** [comment]
Nice!

**Comment by lostdesign** [comment]
The typography needs more contrast and hierarchy but it looks great overall

**Comment by Shackelford-Arden** [comment]
Personally, I'm a bit fan of the increased usage of the available space. Definitely excited!

**Comment by Tzeenchist** [comment]
I think it would be cool to visualize the connection of books and shelves in the form of a graph.

**Comment by jorgedeloera** [comment]
There is some design file on which they are based (sketchapp, figma or something)?
I am ux designer, i can help.

**Comment by ssddanbrown** [comment]
Made some good progress this weekend, Most views have now been converted to the new design but a lot of additional functionality, improvements, fixing and tidying still to do. 

@jorgedeloera No design files I'm afraid, designing directly in code :grimacing:.

Here's another preview:

**Old Profile View**
bookstackdev com_settings_users_1 1

**New Profile View**
bookstackdev com_settings_users_1

**Comment by MrSnoozles** [comment]
Looks really nice and cleaned up 👍 Can't wait  :)

**Comment by edenpc** [comment]
Looks really great!

**Comment by chou0214** [comment]
can't wait for the new layout

**Comment by tranthon** [comment]
When would you release this 2019 design version?

**Comment by ssddanbrown** [comment]
Have been playing about with a more unique & efficient `/shelves` list view, Where all books are directly listed in columns, kind of like real-life shelves. Grid view will remain as a more visual overview.

bookstackdev com_shelves

**Comment by Nebucatnetzer** [comment]
Looks good :)

**Comment by Nebucatnetzer** [comment]
About improving the mobile usability. When I notice something that doesn't work properly on a mobile device due to the design. E.g. that something doesn't fit on the screen. Should I open a new issue for it or post it here?

**Comment by ssddanbrown** [comment]
@Nebucatnetzer Probably best to open a new issue, but please don't raise anything for now since things are rapidly changing and/or unfinished. At some point I'll merge this into master for testing, translations and review at which point issues can be created.

**Comment by Nebucatnetzer** [comment]
I didn't notice the problems in the new design but in the old design and I don't know what exactly you plan to change in the mobile layout with the new design.

**Comment by ssddanbrown** [comment]
@Nebucatnetzer Okay, The structure of all views will effectively be completely different on mobile after the redesign so hold off for now until merged.

**Comment by Abijeet** [comment]
> Have been playing about with a more unique & efficient `/shelves` list view, Where all books are directly listed in columns, kind of like real-life shelves. Grid view will remain as a more visual overview.

@ssddanbrown - This looks very clean and well spaced out. Are you planning to let people collapse / expand the book list under a shelf?

**Comment by ezzra** [comment]
> so hold off for now until merged.

I know thats a boring question, but do you have any ideas when your will be able to merge this? Iam currently planning to reorganize the structure of my bookstack and would like to do it together with the new design to make it less confusing for my users.

**Comment by ssddanbrown** [comment]
> Are you planning to let people collapse / expand the book list under a shelf?

@Abijeet Maybe not initially, We'll see based on feedback during testing/release. I like the idea of this shelve-view being a feature of the list view. 

> Also, the Book view has Create new Book before the Grid view action, but on the Bookshelf that's reversed.

@Abijeet Thanks for noting! Will fix, still quite a few inconsistencies to clean up. 

> I know thats a boring question, but do you have any ideas when your will be able to merge this?

@ezzra Not really, Probably another few weekends needed on it. I'll probably want to do a v0.25.2 release as some point soon too which would delay work on this. Maybe another month or two? That comment was referencing merging into master though which I do not commit to being release-ready. Probably another week or two after merging into master before we'd see the release. 
Will not commit to any timings or make any guarantees though.

**Comment by lynchpatrickj** [comment]
> Have been playing about with a more unique & efficient `/shelves` list view, Where all books are directly listed in columns, kind of like real-life shelves. Grid view will remain as a more visual overview.
> 
> bookstackdev com_shelves

Any chance we could get tags and categories to show up alongside the title? Would be nice if these had a color assigned also.

**Comment by ssddanbrown** [comment]
Getting there: https://gfycat.com/acceptablewanarkshell

Have had good progress over these last two weekends. Just a few small bits and an update to the mobile styles now before it's ready to be merged into master.

**Comment by Abijeet** [comment]
@ssddanbrown - Looks good!

A few things,

1. Padding on the top of the page, between the page heading and the border of the white main section feels a little high.
2. Having the create buttons along with the other buttons that are specific to the page (Edit, Delete etc) we are currently viewing feels a little awkward. Maybe we can add a horizontal divider?
3. On the same menu, how are we deciding the order of the menu items?

**Comment by JHenneberg** [comment]
> Getting there: https://gfycat.com/acceptablewanarkshell
> 
> Have had good progress over these last two weekends. Just a few small bits and an update to the mobile styles now before it's ready to be merged into master.

Really good progress. Cant wait.

**Comment by ssddanbrown** [comment]
@Abijeet 

> 1. Padding on the top of the page, between the page heading and the border of the white main section feels a little high.

Yeah, I've had a surprising amount of trouble with this padding, It never looks quite right depending on the page content. Will likely adjust this again before release.

> 2. Having the create buttons along with the other buttons that are specific to the page (Edit, Delete etc) we are currently viewing feels a little awkward. Maybe we can add a horizontal divider?

Good idea, Some visual separation would really help here.

> 3. On the same menu, how are we deciding the order of the menu items?

Not really decided yet. The ordering is something I know will change before release. It feels odd to not have the edit page action at the top. At some point I'll put some focus on this, probably at the same time as your idea from point 2.

**Comment by ssddanbrown** [comment]
Upon other bits, I've done some updates to the mobile layout today. 

Here's a preview of what this looks like, I've followed the same flow for the exact same content at iPhone SE sizes (Our smallest target):

* Old Design: https://gfycat.com/EminentExhaustedFinch
* New Design: https://gfycat.com/esteemedfrighteningazurevase

Actually got stuck a few times on the old design. I know there's still some padding/size changes for mobile still to do. Still need to update Markdown editor for mobile.

**Comment by ssddanbrown** [comment]
If anyone has some better recommendations for the wording (Or good ideas for icons) of the info/content tabs that would be great:

bookstack local_books_all-about-bookstack_page_bookstack-general-usage(iPhone 5_SE)

Info will show everything that's currently in the sidebar and any buttons/actions. Contents focuses on the main content

**Comment by Nebucatnetzer** [comment]
Looks a lot cleaner, however we'll notice what could be improved when we use it in production :)

**Comment by ezzra** [comment]
Much better, but the header is still too large, the breadcrumb row is too big and I wonder if there is even a possibility to hide it somewhere else?!

**Comment by ssddanbrown** [comment]
After 6 Months from starting this redesign, I'm fairly happy with where it's got to. Will still be some tweaks and fixes to make while other bits are completed for the next release. Now happy to merge into master.

Feel free to open new issues regarding the design if you're comfortable playing with the master branch, Please prefix the issue names with `[2019 design]` so I can easily see if the issue is regarding this design. Be aware that UI stuff is very opinionated and subjective so sorry if I close any such issues more hastily than you'd hope.

**Comment by nmehlei** [comment]
After switching to the new version, the tiles of the grid view in our books list have now a maximum width of ~262px with the book titles h2 element having a maximum width of 214px. This leaves only ~19 characters before the title is being wrapped. Is this expected behavior? At least in our case, it negatively impacts the visual look but this probably depends on the average book length and might be very different in other cases.

**Pull request merged**
