### PR TITLE
add German informal language

### PR DESCRIPTION
**Pull request by ezzra**
This commit adds German informal language ("Du" instead of "Sie") based on the current formal language files. Fixes this part of #890.

### CODE REVIEW

**Comment by ezzra** [comment]
> Not even they appear to directly support this.

but both of them use the informal "Du" and not the formal "Sie" like here ;) But even wordpress introduced formal "Sie" language variant finally some month before. Its actually an issue, in coding communities for example its very much common to use informal "Du", thats why I think Gitlab will not introduce the formal language. But in Wordpress the users are not part of any community, so its quite right to offer also the formal language variant.

However, you could rather consider not offering the formal language, but not offering the informal language would be wrong. But you are completely right, it would be much better if one would be based on the other, but it looks like there is only one fallback in laravel translation system?!

**Comment by ezzra** [comment]
I just force-pushed the new variant with dependence on the formal german language files. I still dont know how to care for the comments within the files where no more language settings exists, in my opinion they could be removed. And maybe there should be a comment in each file, that this is depending on `lang/de`

How do you think about this new approach  @ssddanbrown ?

**Comment by ssddanbrown** [comment]
@ezzra Looks good. Yeah, I'd probably remove any comments they don't have any translations under them.

Looking at the core laravel `Illuminate\Translation\Translator` class I think it'd be fairly easy to extend to add 'baseLanguage' support. Would also need to setup a custom provider to implement it but simple extend the existing one. This would be a nice step to remove any logic from these translation files and align with how the existing fallback works.

I'd be happy to set this up after merge though.

**Comment by ezzra** [comment]
I would definitely prefer that, even if this here an ok solution, it's not really nice that it doesn't get any simpler. I was also surprised that the language system doesn't offer that option.

I removed the comments, but it's also not really nice that there is apparently no uniform way in the files how the comments should be formatted. Some are just `// pages` others are     
```
/**
* Password Reset
*/`
```

etc.

**Comment by ssddanbrown** [comment]
Now merged. As said above, I tweaked the implementation and added tests to cover in 323bff7d6d3974e5752bfec9581d733b91e933f5.

Yeah, Would be good to standardise the comments at some point. Am looking to update the translation helper script at some point to match `en` line numbers and comments so it will be standardised when I get around to that.

Thanks again for opening this pull request @ezzra

**Pull request merged**
