### PR TITLE
enh(recently updated): show updatedBy and updated_at

### PR DESCRIPTION
**Pull request by Julesdevops**
See https://github.com/BookStackApp/BookStack/issues/3045 for informations

### CODE REVIEW

**Comment by mlipok** [comment]
I just sent it to my WebDev to check this.

**Comment by mlipok** [comment]
It looks good for me:
image

**Comment by mlipok** [comment]
btw.
As you can see this shows only "Page" name for example "TYMCZASOWE" or "Screenshoty"
could you also think about adding a feature to provide more precise localization something like "Shelf / Book / Chapter / Page"

btw.
Should I open new FeatureRequest for this ?

**Comment by Julesdevops** [comment]
It may be out of scope for this PR but this could be a useful enhancement imo. Waiting for insights from the maintainers about this

**Comment by mlipok** [comment]
So I open new FeatureRequest

**Comment by ssddanbrown** [comment]
Thanks for this @Julesdevops, All looked great. I followed this up with a test to cover the change in aae3cd69d7b3820aeff1c5fb40cd73b1cc84f4fd.

Merged to be part of the next patch release.

**Comment by Julesdevops** [comment]
Thanks, and apologies for the missing test, totally forgot for this one

**Pull request merged**
