### PR TITLE
Spanish translation completed

### PR DESCRIPTION
**Pull request by diegoseso**
I have finished the first effort I made to have a full translation to spanish of this great application so we can have it 100% translated.

### CODE REVIEW

**Comment by ssddanbrown** [comment]
Hello again @diegoseso. Thank you for this, It's much appreciated. I will merge these updates in before the next release.

**Comment by ssddanbrown** [comment]
Hi @diegoseso,

Do you know what encoding your text is in? A lot of characters are showing up incorrectly in my text editor and I can't seem to automatically convert it. I've tried manually but I'm worried I'm making a lot of mistakes.

**Comment by diegoseso** [comment]
I will, did no realized about that since I always use vim, let me that work
to me and I will make It right,
Regards

**Comment by diegoseso** [comment]
hello @ssddanbrown I have just fixed the encoding trouble, thanks for your patience

**Comment by ssddanbrown** [comment]
@diegoseso No worries at all, Thanks again for doing these translations. Will merge in now for v0.16 which will hopefully be released this weekend.

**Pull request merged**
