### PR TITLE
Translation of all messages from english to brazilian portuguese

### PR DESCRIPTION
**Pull request by NakaharaL**
[pt_br.zip](https://github.com/BookStackApp/BookStack/files/701431/pt_br.zip)

Hello,

This is the translation of all messages within Bookstack from english to brazilian portuguese. I should say that the brazilian portuguese is somewhat different from the portuguese spoken in Portugal. So, this version is intended for the brazilian public.

### CODE REVIEW

**Comment by ssddanbrown** [comment]
@NakaharaL Oh wow, Thank you for your hard work, this is amazing!

Unfortunately this pull request is configured wrong so I cannot merge this in but I can do it manually with the content in your zip. Doing this manually means you won't show as contributor on GitHub. If you don't care about that let me know and I'll merge in this translation manually otherwise I'd be happy to guide you through creating the pull request.

**Comment by NakaharaL** [comment]
Hey! How do you do? Well, I would be very happy if you could guide me on how to correctly contribute to BookStack. 

See, this was my very first contribution on any github project and I would be very glad to have my name there, if it's not much to ask. 

If you guide me I'll push the update tomorrow first thing. 

Thanks!

**Comment by ssddanbrown** [comment]
Hi @NakaharaL, That's fine. Here's a really good general guide to creating a pull request on github:
https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github

To summarise, Here are the steps you'll need to perform:

1. Create a fork of the BookStack project by going to the [project homepage](https://github.com/BookStackApp/BookStack) and clicking the 'fork' button at the top-right. This will create your own copy of the project at https://github.com/NakaharaL/BookStack.
2. Via git, Clone your copy of the project down to your computer.
3. Add your language files to a `resources/lang/pt_br` folder.
4. Commit your additions via git then push the change to your personal NakaharaL/BookStack repository.
5. On GitHub, Go to your own BookStack repo then press 'New pull request'.
6. On the left select your 'NakaharaL/BookStack' repo and the branch you pushed to (Likely master). On the right select 'ssddanbrown/BookStack' and the 'master' branch. Then click 'Create Pull Request' and then give it a name and brief description.

If you're not experienced with using git then slowly go through the above digitalocean tutorial as it takes you through the commands and terminology. Alternatively, There is the [GitHub desktop application](https://desktop.github.com/) if you really don't like the command line but I've never tried creating a pull request through it so I can't help out with that too much.

If you get stuck at any stage just comment here as I'm happy to help.

**Comment by NakaharaL** [comment]
Thank you Dan!

I have followed your instructions and I think now the pull is correct and ready to be integrated to bookstack. 

Thanks!

**Pull request closed without merging**
