### PR TITLE
Add Tag page.

### PR DESCRIPTION
**Pull request by jacac**
Regarding #738.

### CODE REVIEW

**Comment by jacac** [comment]
@ssddanbrown Any comments if this tag page could be added?  I've attached a screenshot of the tag page.
image

**Comment by ssddanbrown** [comment]
Thanks @jacac,
Sorry I have not responded sooner, This comes at a bit of an awkward time with the redesign (#1153) in progress.

It looks good! I think we'll need to evaluate the best place for this to sit in BookStack along with how we ensure it adds value. Will also need some edits to the code along with merging into the redesign. 

Probably won't be until after the redesign release that I can properly review this.

**Comment by fklappan** [comment]
Sorry for thread necroing, but is this still relevant/doable? Some kind of "tag UI" would be great.

**Comment by ssddanbrown** [comment]
Since this is relatively old I'm going to close this off, Although I appreciate that's due to my lack of review.

I'm still open to such a page being added, but it'd need to have a little more purpose than simply a list of tag names. I think the number of usages of that tag and the number of unique values used, for that tag, would be a good start since then it can provide an idea of utilisation. 

In terms of UI, A paginated tabular list may work better here than being alphabetical breakdown, especially when considering potential emoji and non-ascii usage.

**Pull request closed without merging**
