### PR TITLE
Book Coverart and Grid Display

### PR DESCRIPTION
**Pull request by bharadwajag**

### CODE REVIEW

**Comment by bharadwajag** [comment]
@ssddanbrown @Abijeet 
We've implemented #434 
Here you can see the latest changes - https://gfycat.com/UncomfortableSpanishHamadryad
Please let us know your comments.

**Comment by ssddanbrown** [comment]
I must admit, When I saw the preview when the pull request was initially made I was very apprehensive about this feature but looking at the above gfycat preview this really does look great. Great work, Truly. Love how it fits in with the design update coming the the next release.

One question, What's the different between this pull request and the other one on #434?

The next release, v0.18, I think has enough new features in and is coming to a close so I'll probably look to merge this into the release after. I haven't look at the code yet but I'll have a deeper dig at merge time.

**Comment by aljawaid** [comment]
This looks amazing, can it be added to the PDF too? or at least have an option to include in export to pdf

**Comment by ssddanbrown** [comment]
Really sorry for my massive delay in reviewing this. I've now started to plan up the next release as a milestone and allocated this feature to it.

The only thing I'd like to do is move the `books_view_type` value off of the user model and use the 'settings' system instead to match how language preferences are stored (This format should be more scalable as more user preferences are added).

I'm happy to make this change after merging unless you want to do it beforehand?

**Comment by bharadwajag** [comment]
@ssddanbrown 
No issues from my end.

**Comment by ssddanbrown** [comment]
Thanks again to everyone involved with this. Now merged into master for next release.

**Comment by bharadwajag** [comment]
Thank you @ssddanbrown , @Abijeet and @nileshdeepak .

**Pull request merged**
