### PR TITLE
chore(dev): add xdebug support for docker setup

### PR DESCRIPTION
**Pull request by bourdaisj**
Add xdebug support in the docker compose setup.
Works well with my my setup (vscode), should work fine for other IDE as well.

If this looks good, I will provide documentation in the README.md and other relevant places (?).

### CODE REVIEW

**Comment by ssddanbrown** [comment]
Thanks for this @Julesdevops,
Have tested on a PHPStorm setup and it seems to work well.

I did notice that the `xdebug.start_with_request=yes` which will activate xdebug on every request which will slow things down a bit when debugging. Probably notthing to worry about now but if people report slow development environments using the docker setup, this might need to change to be [manually/extension initiated](https://xdebug.org/docs/step_debug#web-application) instead.

In regards to any documentation, keep it brief/high-level where possible. Don't want to fill the readme with instructions for each possible editor or anything.

**Comment by Julesdevops** [comment]
@ssddanbrown Thx for feedback, I updated the readme.
Agree for the start_with_request option. I will be here to improve it if contributors reports slow development environments. :)

**Comment by ssddanbrown** [comment]
Now merged, thanks again @Julesdevops

**Comment by esakkiraja100116** [comment]
#4187 - Can you look at this issue @Julesdevops ?

**Pull request merged**
