### PR TITLE
Add twitch socialite auth provider

### PR DESCRIPTION
**Pull request by moutonnoireu**
Followed some of the recent socialite added providers (okta, etc). It should work without any problems. If somebody could test ? 👍

### CODE REVIEW

**Comment by lommes** [comment]
Currently the entry in composer.json is missing which leads to failing tests.

**Comment by moutonnoireu** [comment]
Forget to run a ``composer update`` to update ``composer.lock``.

**Comment by lommes** [comment]
Thanks for your work!

I just tested this PR and it worked for me! Only thing that would be nice is to change the keys in .env and config/services.php to match those of other services. 

TWITCH_KEY should become TWITCH_APP_ID
TWITCH_SECRET should become TWITCH_APP_SECRET

The TWITCH_REDIRECT is not needed in .env since it will be the same for each install of bookstack. It can bet set in config/services.php:

```
'twitch' => [
        'client_id' => env('TWITCH_APP_ID'),
        'client_secret' => env('TWITCH_APP_SECRET'),
        'redirect' => env('APP_URL') . '/login/service/twitch/callback',
        'name'          => 'Twitch',
    ],
```

**Comment by moutonnoireu** [comment]
Made modifications following your inputs @lommes ;)

**Comment by lommes** [comment]
There seem to be an issue with the svg file, which is displayed way too large.

**Comment by moutonnoireu** [comment]
I reduced the icon size. Was thinking the svg was used dynamically :)

**Comment by lommes** [comment]
In my opinion this can be merged if the icon thing is changed.

**Comment by ssddanbrown** [comment]
Thanks both for your efforts on this! I've marked this to be in the next release.

Just one thing I noticed looking over the code, The SVG icon appears to simply be a png embedded within an SVG. It would be great if this was an actual SVG drawing.

I'd be happy to make that change before merging but I'll leave this open until then in case you want to make this change yourself.

**Comment by moutonnoireu** [comment]
I'de be happy if you could do it, i'm not very familiar with svg. :)

**Comment by ssddanbrown** [comment]
SVG updated and now merged in, Thanks, Works great!

**Pull request merged**
