### PR TITLE
Dirty feed

### PR DESCRIPTION
**Pull request by ezzra**

### CODE REVIEW

**Comment by nekromoff** [comment]
I have tested it by mergin your "add dirty feed code" into the latest BookStack code and it does not work for me, gives me 404 when accessing feed URL.

**Comment by nekromoff** [comment]
error log:

```
[2018-12-09 15:42:31] production.ERROR: Object doesn't implement `Spatie\Feed\Feedable` {"userId":1,"email":"xxxxxx","exception":"
[object] (Spatie\\Feed\\Exceptions\\InvalidFeedItem(code: 0): Object doesn't implement `Spatie\\Feed\\Feedable` at /var/www/html/wiki/vendor/spati
e/laravel-feed/src/Exceptions/InvalidFeedItem.php:15)
[stacktrace]
#0 /var/www/html/wiki/vendor/spatie/laravel-feed/src/Feed.php(78): Spatie\\Feed\\Exceptions\\InvalidFeedItem::notFeedable(Object(BookStack\\Action
s\\Activity))
#1 /var/www/html/wiki/vendor/spatie/laravel-feed/src/Feed.php(61): Spatie\\Feed\\Feed->castToFeedItem(Object(BookStack\\Actions\\Activity))
#2 [internal function]: Spatie\\Feed\\Feed->Spatie\\Feed\\{closure}(Object(BookStack\\Actions\\Activity), 0)
#3 /var/www/html/wiki/vendor/laravel/framework/src/Illuminate/Support/Collection.php(861): array_map(Object(Closure), Array, Array)
#4 /var/www/html/wiki/vendor/spatie/laravel-feed/src/Feed.php(62): Illuminate\\Support\\Collection->map(Object(Closure))
#5 /var/www/html/wiki/vendor/spatie/laravel-feed/src/Feed.php(30): Spatie\\Feed\\Feed->resolveItems(Array)
#6 /var/www/html/wiki/vendor/spatie/laravel-feed/src/Http/FeedController.php(19): Spatie\\Feed\\Feed->__construct('BookStack Feed', 'https://int.b
as...', 'BookStack\\\\Actio...', 'feed::feed')
#7 /var/www/html/wiki/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(48): Spatie\\Feed\\Http\\FeedController->__invoke('
analytika')
#8 /var/www/html/wiki/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(I
lluminate\\Routing\\Route), Object(Spatie\\Feed\\Http\\FeedController), '__invoke')
```

**Comment by ezzra** [comment]
mh did you really merge it successfully? It looks like the Actions/Activity.php was not updated. Line 17 within this file should be

`class Activity extends Model implements Feedable`

**Comment by ezzra** [comment]
ok unfortunately Github is not updating to new commits in the branch when the PR is closed. So I do it manually here:

* [commited](https://github.com/ezzra/BookStack/commit/1a5311b07b75fe06d828a64ddf72e6648e7cdfab): dirty-feed add comment track to feeds

**Comment by nekromoff** [comment]
Now it works, thanks. I have updated both the line you mentioned (no
change) and the file itself (works).

**Comment by nekromoff** [comment]
However: there is no general feed for the latest changes at the root `/public/` URL.

I would therefore iterate over all book feeds to find all latest changes, which is not feasible.

I am going to mod your update to provide for the latest changes for the whole wiki.

**Comment by ezzra** [comment]
of course, go forward! I also added the filtersimilar behavior, because I was spammed by page update messages :)

- [commited](https://github.com/ezzra/BookStack/commit/fc795fad8c817ce48b73b945570d4d327da9d466): dirty-feed filter similiar activities

**Pull request closed without merging**
